### ISSUE TITLE
from scHPL import progressive_learning

### ISSUE THREAD

**Issue by XiuanZhang** [lcmmichielsen/hierarchicalprogressivelearning#4]
Hello! 

I believe scHPL is a wonderful package to  process data from multi-samples. 
But i met some question with your example data. I failed to find out the file "progressive_learning.py" when i ran "from scHPL import progressive_learning".
Can you help me to address this problem?

Regards,
Shaun

**Comment by lcmmichielsen** [comment]
Hi Shaun,

This function was called `progressive learning` in version 0.02 but is called `learn` in the new version. I haven't updated the vignettes. You can find these new names in the documentation, basic tutorial, or treeArches notebooks. Sorry for the confusion!
