### ISSUE TITLE
treeArches.zip corrupted

### ISSUE THREAD

**Issue by drbecavin** [lcmmichielsen/hierarchicalprogressivelearning#6]
Hello
Great work !
We tried to do the tutorial but treeArches.zip  downloaded from here https://zenodo.org/record/6786357#.ZA8E3OzMKWZ is corrupted. It is impossible to extract the files from it.
Can you check.
Thanks

**Comment by lcmmichielsen** [comment]
Hi! You can unzip the files in two ways: either use the extract tool in windows or run `7za x treeArches.zip` in Linux. I just double-checked and both options work. Thanks for letting me know though, I will add this explanation to the tutorial.

**Comment by drbecavin** [comment]
Worked like a charm !
Thank you for the quick answer.
