### ISSUE TITLE
Training with only one reference

### ISSUE THREAD

**Issue by tvegawaichman** [lcmmichielsen/hierarchicalprogressivelearning#7]
Hello! I want to pre-train scHPL but only with one reference.
I have two questions:
Should the input anndata be normalized?
If it is, I'll be using the conventional normalization in scanpy: 

```
adata = ad.AnnData(X = ref,
                   obs = dict(obs_names=ref.index.astype(str)),
                   var = dict(var_names=ref.columns.astype(str))
                   )
adata.var_names_make_unique()
adata.obs_names_make_unique()

sc.pp.normalize_total(adata, target_sum=1e4)
#Logarithmize the data:
sc.pp.log1p(adata)
## Add my labels
adata.obs = labels 
```

When I want to train the model, it asks me to add a batch, but since I only have one, I use this:
```
adata.obs['batch'] = '0'

tree = learn.learn_tree(data = adata,
                        cell_type_key = 'label',
                        classifier = 'svm',
                        batch_key = 'batch',
                        batch_order = [0],
                        dimred = False)

```

But it throws me this error:
ValueError: Found array with 0 sample(s) (shape=(0,)) while a minimum of 1 is required.

Thanks!

**Comment by lcmmichielsen** [comment]
Hi!

- I advise normalizing data. Usually, I use the standard scanpy pipeline as well, so that should be fine.
- The way you encode the batch should work. There's a small mistake in your code though: you encode the batch as a string ('0'), but give it to the function as an integer (no quotation marks). Making it consistent will solve the problem I think. 


Good luck! Let me know if you have any further questions.

**Comment by tvegawaichman** [comment]
Hello! 
Perfect, I did it but now I'm getting an empty tree:
```
>>> tree
([Node("['root']")], [])

```
And when I tried to run the prediction it gives me:
```
y_pred1 = predict.predict_labels(query,tree)
if tree[0].get_RE() > 0:
       ^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get_RE'
```

Thanks!

**Comment by lcmmichielsen** [comment]
I think the problem is with the learn_tree function. It assumes that there are multiple batches and iteratively adds them. If there are less than two, the first tree is never trained. A better option for training your tree is using the following steps:

- Create the tree. If you know the structure of the tree in Newick format, you can use the scHPL.utils.create_tree function. Otherwise, you could use the following to create a flat tree (so no hierarchy)

```
tree = create_tree('root')
tree = _construct_tree(tree, labels)

def _construct_tree(tree, labels):
    unique_labels = np.unique(labels)
    
    for ul in unique_labels:
        newnode = TreeNode([ul])
        tree[0].add_descendant(newnode)
        
    return tree
```

- Train the tree using the scHPL.train.train_tree() function.

Good luck!

**Comment by tvegawaichman** [comment]
I tried with _construct_tree, but the function returned me an empty tree.


```
>>> tree
[Node("['root']")]

>>>_construct_tree(tree,labels)
[Node("['root']")]
```

And labels is not empty, it is a dataframe...
```
>>> labels
                                  label
10X156_7:GTCACAACATGCAATC        Neuron
10X208_5:CTCGAGGGTAGAATAC  Neuronal IPC
10X163_8:CACAACAGTAATGCTC        Neuron
10X164_6:ATGGGTTCATAATCGC   Radial glia
10X152_8:TGCGGGTAGCTCAACT   Radial glia
...                                 ...
```

I ran some tests, and it could be that the problem occurs when the function add_descendant(newnode) since it is not adding any node 

Thanks!

**Comment by tvegawaichman** [comment]
Sorry, it was my mistake! I have plotted the tree, and it works perfectly!
I want to take advantage of this opportunity to ask if there exists an option to parallelize. Thank you very much!

**Comment by lcmmichielsen** [comment]
Glad to hear that it works!

At the moment nothing is parallelized in the code. If you're willing to implement this and have questions about the code, I am happy to answer them.

**Comment by tvegawaichman** [comment]
Okay! It was just curiosity!
For now, everything works perfectly. In the future, maybe I will come back with more questions!
Many thanks for your help!

**Comment by sarah-chapin** [comment]
I am also trying to run the above code to construct a tree on a single reference: 

```
tree = create_tree('root')
tree = _construct_tree(tree, labels)

def _construct_tree(tree, labels):
    unique_labels = np.unique(labels)
    
    for ul in unique_labels:
        newnode = TreeNode([ul])
        tree[0].add_descendant(newnode)
        
    return tree
```
I am also receiving a blank tree as output, as @tvegawaichman did initially:
`[Node("['root']")]`

@tvegawaichman - Do you remember what correction you made to the code to resolve this error?

**Comment by tvegawaichman** [comment]
Hello! When I printed it, it looked like an empty tree, but when I plotted it, I found that it actually wasn't. I then used that tree for training. 
Here is an example of how I applied it:
https://github.com/fungenomics/scCoAnnotate/blob/main/Scripts/scHPL/train_scHPL.py

**Comment by sarah-chapin** [comment]
@tvegawaichman Thanks! This was very helpful.
